include theos/makefiles/common.mk

BUNDLE_NAME = TerminalActivatorSettings
TerminalActivatorSettings_FILES = TerminalActivatorSettings.mm
TerminalActivatorSettings_INSTALL_PATH = /Library/PreferenceBundles
TerminalActivatorSettings_FRAMEWORKS = UIKit
TerminalActivatorSettings_PRIVATE_FRAMEWORKS = Preferences
TerminalActivatorSettings_LDFLAGS = -lactivator

TerminalActivatorSettings_IPHONEOS_DEPLOYMENT_VERSION = 4.0

include $(THEOS_MAKE_PATH)/bundle.mk